### ISSUE TITLE
Add Delete method

### ISSUE THREAD

**Issue by wojas** [PowerDNS/simpleblob#1]
Add the following method to the `Interface`:

```go
    Delete(ctx context.Context, name string) error
```

Also implement it in all backends and add relevant tests to the tester.

This is expected to be the last change to the Interface before publication.

## Alternative: optional interface

We could also decide to make this method optional for backends to implement. In this case we would probably end up with:

```go
type Deleter interface {
    Delete(ctx context.Context, name string) error
}

var (
    ErrNotImplementer = errors.New("not implemented")
)

// Delete calls the Delete method if the storage backend implements the Deleter interface,
// or returns ErrNotImplemented if the backend does not support this interface.
func Delete(ctx context.Context, st Interface, name string) error
```

**Comment by ahouene** [comment]
#6, solving this issue, has just been merged.
